[alias] # command aliases
install_soroban = "install --git https://github.com/AhaLabs/soroban-tools --rev dc2a543993a293155516df52e79cc120cbd3dfe0 --root ./target soroban-cli --debug --features opt"
b = "build --release --target wasm32-unknown-unknown"
